name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        if_key_exists: ignore
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: copy .env
      run: echo -e "
       APP_ENV=${{ secrets.APP_ENV }}\n
       BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}\n
       BINANCE_SECRET_KEY =${{ secrets.BINANCE_SECRET_KEY  }}\n
       POSTGRES_DB=${{ secrets.POSTGRES_DB }}\n
       POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}\n
       POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}\n
       POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}\n
       POSTGRES_USER=${{ secrets.POSTGRES_USER }}\n
       TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
    - name: Deploy with rsync
      run: rsync -avzr .env docker-compose.prod.yml scripts root@${{ secrets.SSH_HOST }}:/root/lamboWorkshop/
   